import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'
import { sendEmail } from '@/lib/email/send'

export const runtime = 'nodejs'

// ─── GET /api/inspections?draw_request_id=xxx ────────────────────────────────
export async function GET(request: NextRequest) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single()
  if (!profile || !['admin', 'lender'].includes(profile.role)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const drawId = request.nextUrl.searchParams.get('draw_request_id')
  if (!drawId) return NextResponse.json({ error: 'draw_request_id required' }, { status: 400 })

  const { data, error } = await supabase
    .from('inspections')
    .select('*')
    .eq('draw_request_id', drawId)
    .order('created_at', { ascending: false })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ data })
}

// ─── POST /api/inspections ────────────────────────────────────────────────────
export async function POST(request: NextRequest) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single()
  if (!profile || profile.role !== 'admin') {
    return NextResponse.json({ error: 'Admin only' }, { status: 403 })
  }

  const body = await request.json()
  const { draw_request_id, project_id, inspector_name, inspector_email, scheduled_date } = body

  if (!draw_request_id || !inspector_name || !inspector_email) {
    return NextResponse.json({ error: 'draw_request_id, inspector_name, inspector_email required' }, { status: 400 })
  }

  // Fetch draw + project info for the email
  const { data: draw } = await supabase
    .from('draw_requests')
    .select('request_number, amount, projects(name, address, city, state)')
    .eq('id', draw_request_id)
    .single()

  // Insert inspection — token is auto-generated by DB default
  const { data: inspection, error } = await supabase
    .from('inspections')
    .insert({
      draw_request_id,
      project_id: project_id ?? (draw as any)?.projects?.id,
      inspector_name,
      inspector_email,
      scheduled_date: scheduled_date || null,
      created_by: user.id,
    })
    .select()
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Send inspection request email to the inspector
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://www.buildchain.finance'
  const portalUrl = `${baseUrl}/inspect/${inspection.token}`
  const project = (draw as any)?.projects

  try {
    await sendEmail({
      to: inspector_email,
      subject: `Inspection Request — ${project?.name ?? 'BuildChain Project'} · ${draw?.request_number ?? ''}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0d1b2a; color: #e8edf2; padding: 32px; border-radius: 12px;">
          <div style="font-size: 24px; font-weight: 900; margin-bottom: 4px;">
            Build<span style="color: #c9a84c;">Chain</span>
          </div>
          <div style="font-size: 12px; color: #6b8198; margin-bottom: 24px; text-transform: uppercase; letter-spacing: 1px;">
            Inspection Request
          </div>

          <h2 style="font-size: 18px; font-weight: 700; margin: 0 0 8px;">Hello ${inspector_name},</h2>
          <p style="color: #9ab0c7; margin: 0 0 24px;">
            You have been assigned to inspect the following construction draw:
          </p>

          <div style="background: rgba(255,255,255,0.05); border: 1px solid #1e3a50; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
            <div style="font-size: 13px; color: #6b8198; margin-bottom: 4px;">PROJECT</div>
            <div style="font-weight: 700; font-size: 16px; margin-bottom: 12px;">${project?.name ?? '—'}</div>

            <div style="font-size: 13px; color: #6b8198; margin-bottom: 4px;">ADDRESS</div>
            <div style="margin-bottom: 12px;">${[project?.address, project?.city, project?.state].filter(Boolean).join(', ') || '—'}</div>

            <div style="font-size: 13px; color: #6b8198; margin-bottom: 4px;">DRAW REQUEST</div>
            <div style="margin-bottom: 12px;">${draw?.request_number ?? '—'}</div>

            ${scheduled_date ? `
            <div style="font-size: 13px; color: #6b8198; margin-bottom: 4px;">SCHEDULED DATE</div>
            <div style="margin-bottom: 12px;">${new Date(scheduled_date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}</div>
            ` : ''}
          </div>

          <p style="color: #9ab0c7; margin-bottom: 20px;">
            After completing your on-site inspection, please submit your report using the secure portal link below:
          </p>

          <a href="${portalUrl}"
            style="display: inline-block; background: #c9a84c; color: #0d1b2a; font-weight: 700; padding: 14px 28px; border-radius: 8px; text-decoration: none; font-size: 15px;">
            Submit Inspection Report →
          </a>

          <p style="color: #6b8198; font-size: 12px; margin-top: 24px;">
            This link is unique to you and expires with the inspection request.
            If you have questions, reply to this email.
          </p>
        </div>
      `,
    })
  } catch (emailErr) {
    console.warn('[Inspections] Email send failed (non-fatal):', emailErr)
  }

  // Log to activity
  await supabase.from('activity_log').insert({
    action: 'inspection_assigned',
    user_id: user.id,
    details: { inspector_name, inspector_email, draw_request_id, inspection_id: inspection.id },
  }).throwOnError().then(() => {}).catch(() => {})

  return NextResponse.json({ data: inspection }, { status: 201 })
}
